FROM jenkinsci/blueocean

# COPY tmp/plugins.txt /tmp/plugins.txt

# RUN /usr/local/bin/plugins.sh /tmp/plugins.txt

COPY usr/share/jenkins/ref /usr/share/jenkins/ref

CMD ["--prefix=/jenkins"]

#Add OpenJDK 11
#Add OpenJDK 8
#Add Node LTS and LTS-1

#Add Maven 
#Add gradle
#Add cf
#Add kubectl
